# API Server Configuration

[server]
host = "127.0.0.1"
port = 9090

[database]
url = "postgresql://postgres:5432/rustar-api?user=postgres&password=postgres"
pool_size = 1

[message_broker]
host = "mosquitto"
port = 1883
keep_alive = 60
