-- PostgreSQL database dump
-- Name: ground_stations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ground_stations (
    id bigint NOT NULL,
    name text NOT NULL,
    location double precision,
    altitude bigint
);


--
-- Name: ground_stations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ground_stations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ground_stations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.jobs (
    id bigint NOT NULL,
    sat_id bigint NOT NULL,
    gs_id bigint NOT NULL,
    start timestamp with time zone NOT NULL,
    "end" timestamp with time zone
);


--
-- Name: jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.jobs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: jobs_status_updates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.jobs_status_updates (
    job_id bigint NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    status text NOT NULL
);


--
-- Name: satellites; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.satellites (
    id bigint NOT NULL,
    name text NOT NULL,
    tle text NOT NULL
);


--
-- Name: satellites_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.satellites ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.satellites_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: telemetry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.telemetry (
    id bigint NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    sat_id bigint NOT NULL,
    gs_id bigint NOT NULL,
    payload bytea
);


--
-- Name: telemetry_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.telemetry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.telemetry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ground_stations ground_stations_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ground_stations
    ADD CONSTRAINT ground_stations_id_key UNIQUE (id);


--
-- Name: ground_stations ground_stations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ground_stations
    ADD CONSTRAINT ground_stations_pkey PRIMARY KEY (id);


--
-- Name: jobs jobs_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_id_key UNIQUE (id);


--
-- Name: jobs jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_pkey PRIMARY KEY (id);


--
-- Name: jobs_status_updates jobs_status_updates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jobs_status_updates
    ADD CONSTRAINT jobs_status_updates_pkey PRIMARY KEY (job_id);


--
-- Name: satellites satellites_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.satellites
    ADD CONSTRAINT satellites_id_key UNIQUE (id);


--
-- Name: satellites satellites_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.satellites
    ADD CONSTRAINT satellites_pkey PRIMARY KEY (id);


--
-- Name: telemetry telemetry_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.telemetry
    ADD CONSTRAINT telemetry_id_key UNIQUE (id);


--
-- Name: telemetry telemetry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.telemetry
    ADD CONSTRAINT telemetry_pkey PRIMARY KEY (id);


--
-- Name: jobs jobs_gs_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_gs_id_fkey FOREIGN KEY (gs_id) REFERENCES public.ground_stations(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: jobs jobs_sat_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_sat_id_fkey FOREIGN KEY (sat_id) REFERENCES public.satellites(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: jobs_status_updates jobs_status_updates_job_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jobs_status_updates
    ADD CONSTRAINT jobs_status_updates_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: telemetry telemetry_gs_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.telemetry
    ADD CONSTRAINT telemetry_gs_id_fkey FOREIGN KEY (gs_id) REFERENCES public.ground_stations(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: telemetry telemetry_sat_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.telemetry
    ADD CONSTRAINT telemetry_sat_id_fkey FOREIGN KEY (sat_id) REFERENCES public.satellites(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Note: Row Level Security (RLS) is disabled for local development.
-- If deploying to production with RLS policies, enable it per table:
-- ALTER TABLE public.<table_name> ENABLE ROW LEVEL SECURITY;
--

-- PostgreSQL database dump complete
